# Textos para la app 
TEXTOS = {
    "es": {
        "buscar_pelicula": "🔎 Buscar película:",
        "busqueda_avanzada": "🎛️ Búsqueda avanzada",
        "ordenar_por": "📊 Ordenar por:",
        "ver_favoritos": "Ver favoritos",
        "mostrar_mas": "Siguiente ⏭️",
        "mostrar_menos": "⏮️ Anterior",
        "nav_label": "📖 Navegación:",
        "favoritos_titulo": "⭐ Favoritos",
        "cerrar": "Cerrar",
        "agregar_fav": "Agregar a favoritos",
        "ya_en_fav": "Ya está en favoritos.",
        "agregado_fav": "Agregado a favoritos.",
        "sin_favoritos": "No tienes favoritas todavía.",
        "favoritos_eliminado": " Fue eliminado de favoritos.",
        "sinopsis_no_disp": "Sinopsis no disponible",
        "idioma_cambiado": "El catálogo se cambió a Español.",
        "catalogo_nombre": "🎥 CineSeven",
        "idioma_titulo": "🌐 Idioma",
        "mas_populares": "Más populares",
        "menos_populares": "Menos populares",
        "mayor_calificacion": "Mayor calificación",
        "menor_calificacion": "Menor calificación",
        "mas_nuevas": "Más nuevas",
        "mas_antiguas": "Más antiguas",
        "no_mas": "No hay más películas para mostrar",
        "no_menos":"Ya estás en la primera página",
        "favoritos_no_puede_eliminar" : "No se puede eliminar",
        "confirmar_eliminar_fav": "¿Deseas eliminar de tus favoritos?",
        "genero": "🎭 Género:",
        "director": "🎬 Director:",
        "actor": "⭐ Actor:",
        "filtro_anio": "📅 Filtro de año:",
        "ninguno": "Ninguno",
        "exacto": "Exacto",
        "rango": "Rango",
        "desde": "Desde:",
        "hasta": "Hasta:",
        "aplicar_filtros": "Aplicar filtros",
        "calificacion_minima": "⭐ Calificación mínima:",
        "nivel_popularidad_label": "🔥 Nivel de popularidad:",
        "pop_baja": "Baja",
        "pop_media": "Media",
        "pop_alta": "Alta",
        "pop_muy_alta": "Muy Alta",
        "busqueda_avanzada_titulo": "Búsqueda avanzada",
        "director_label": "Director:",
        "reparto_label": "Reparto:",
        "generos_label": "Géneros:",
        "eliminar": "🗑️ Eliminar",
        "buscar_en_favoritos": "🔎 Buscar en favoritos:",
        "ordenar_favoritos": "📊 Ordenar favoritos por:",
        "titulo_az": "Título (A-Z)",
        "anio": "Año",
        "popularidad": "Popularidad",
        "genero": "Género",
        "fecha_agregado": "Fecha de agregado",
        "mostrando": "Mostrando {start}-{end} de {total} películas",
        "mostrando_favs": "Mostrando {start}-{end} de {total}"
    },
    
    "en": {
    "buscar_pelicula": "🔎 Search movie:",
    "busqueda_avanzada": "🎛️ Advanced search",
    "ordenar_por": "📊 Sort by:",
    "ver_favoritos": "View favorites",
    "mostrar_mas": "Next ⏭️",
    "mostrar_menos": "⏮️ Previous",
    "nav_label": "📖 Navigation:",
    "favoritos_titulo": "⭐ Favorites",
    "cerrar": "Close",
    "agregar_fav": "Add to favorites",
    "ya_en_fav": "Already in favorites.",
    "agregado_fav": "Added to favorites.",
    "sin_favoritos": "You have no favorites yet.",
    "favoritos_eliminado": "Was removed from favorites.",
    "sinopsis_no_disp": "Synopsis not available.",
    "idioma_cambiado": "Catalog changed to English.",
    "catalogo_nombre": "🎥 CineSeven",
    "idioma_titulo": "🌐 Language",
    "mas_populares": "Most popular",
    "menos_populares": "Least popular",
    "mayor_calificacion": "Highest rating",
    "menor_calificacion": "Lowest rating",
    "mas_nuevas": "Newest",
    "mas_antiguas": "Oldest",
    "no_mas": "No more movies to display.",
    "no_menos": "You are already on the first page.",
    "favoritos_no_puede_eliminar": "Could not remove from favorites.",
    "confirmar_eliminar_fav": "Do you want to remove from your favorites?",
    "genero": "🎭 Genre:",
    "director": "🎬 Director:",
    "actor": "⭐ Actor:",
    "filtro_anio": "📅 Year filter:",
    "ninguno": "None",
    "exacto": "Exact",
    "rango": "Range",
    "desde": "From:",
    "hasta": "To:",
    "aplicar_filtros": "Apply filters",
    "calificacion_minima": "⭐ Minimum rating:",
    "nivel_popularidad_label": "🔥 Popularity level:",
    "pop_baja": "Low",
    "pop_media": "Medium",
    "pop_alta": "High",
    "pop_muy_alta": "Very High",
    "busqueda_avanzada_titulo": "Advanced search",
    "director_label": "Director:",
    "reparto_label": "Cast:",
    "generos_label": "Genres:",
    "eliminar": "🗑️ Remove",
    "buscar_en_favoritos": "🔎 Search favorites:",
    "ordenar_favoritos": "📊 Sort favorites by:",
    "titulo_az": "Title (A-Z)",
    "anio": "Year",
    "popularidad": "Popularity",
    "genero": "Genre",
    "fecha_agregado": "Date added",
    "mostrando": "Showing {start}-{end} of {total} movies",
    "mostrando_favs": "Showing {start}-{end} of {total}"
}
}

TEXTOS_LOGIN = {
    "es": {
        "titulo": "🎬 Bienvenido a CineSeven 🎬",
        "pregunta": "¿Deseas registrarte o iniciar sesión?",
        "btn_login": "Iniciar sesión",
        "btn_registro": "Registrarse",
        "email": "Correo electrónico:",
        "password": "Contraseña:",
        "nombre": "Nombre (solo para registro):",
        "aviso_reg": "Completa todos los campos para registrarte.",
        "aviso_login": "Escribe correo y contraseña.",
        "email_invalido": "El correo no es válido.",
        "password_invalida": "La contraseña debe tener mínimo 6 caracteres,\nuna mayúscula, una minúscula y un número.",
        "pw_mostrar": "👁️ Mostrar",
        "pw_ocultar": "🙈 Ocultar",
        "saludo": "✅ Bienvenido {nombre}!",
        "login_incorrecto": "⚠️ Usuario o contraseña incorrectos.",
        "registro_ok": "✅ Usuario registrado correctamente.",

    },
    "en": {
        "titulo": "🎬 Welcome to CineSeven 🎬",
        "pregunta": "Do you want to register or log in?",
        "btn_login": "Login",
        "btn_registro": "Register",
        "email": "Email:",
        "password": "Password:",
        "nombre": "Name (for registration only):",
        "aviso_reg": "Please fill in all fields to register.",
        "aviso_login": "Enter email and password.",
        "email_invalido": "Invalid email address.",
        "password_invalida": "Password must have at least 6 characters,\none uppercase, one lowercase and one number.",
        "pw_mostrar": "👁️ Show",
        "pw_ocultar": "🙈 Hide",
        "saludo": "✅ Welcome back, {nombre}!",
        "login_incorrecto": "⚠️ Incorrect username or password.",
        "registro_ok": "✅ User registered successfully.",


    }
}

ETIQUETAS_REGISTRO = {
    "es": {
        "nombre": "Nombre:",
        "apellido": "Apellido:",
        "nombre_app": "Nombre de app:",
        "email": "Correo electrónico:",
        "password": "Contraseña:"
    },
    "en": {
        "nombre": "Name:",
        "apellido": "Last name:",
        "nombre_app": "App name:",
        "email": "Email:",
        "password": "Password:"
    }
}

TEXTOS_GENEROS = {
    "es": {
        "Action": "Acción",
        "Adventure": "Aventura",
        "Animation": "Animación",
        "Comedy": "Comedia",
        "Crime": "Crimen",
        "Documentary": "Documental",
        "Drama": "Drama",
        "Family": "Familiar",
        "Fantasy": "Fantasía",
        "Foreign": "Extranjera",
        "History": "Historia",
        "Horror": "Terror",
        "Music": "Música",
        "Mystery": "Misterio",
        "Romance": "Romance",
        "Science Fiction": "Ciencia Ficción",
        "Thriller": "Suspenso",
        "Tv Movie": "Película de TV",
        "War": "Guerra",
        "Western": "Oeste"
    },

    "en": {
        "Action": "Action",
        "Adventure": "Adventure",
        "Animation": "Animation",
        "Comedy": "Comedy",
        "Crime": "Crime",
        "Documentary": "Documentary",
        "Drama": "Drama",
        "Family": "Family",
        "Fantasy": "Fantasy",
        "Foreign": "Foreign",
        "History": "History",
        "Horror": "Horror",
        "Music": "Music",
        "Mystery": "Mystery",
        "Romance": "Romance",
        "Science Fiction": "Science Fiction",
        "Thriller": "Thriller",
        "Tv Movie": "TV Movie",
        "War": "War",
        "Western": "Western"
    }
}
